-- CREATE TABLE kprofile(
--   id VARCHAR(255) NOT NULL,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL, 
--   picture VARCHAR(255) NOT NULL,
--   vaults INT NOT NULL,
--   keeps INT NOT NULL,
--   PRIMARY KEY (id)
-- )
-- CREATE TABLE keeps(
--   id INT NOT NULL AUTO_INCREMENT,
--   name VARCHAR(255) NOT NULL,
--   description VARCHAR(255) NOT NULL,
--   keeps INT,
--   views INT,
--   shares INT,
--   img VARCHAR(255) NOT NULL,
--   creatorId VARCHAR(255) NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY (creatorId)
--     REFERENCES kprofile(id)
--     ON DELETE CASCADE
-- )
-- CREATE TABLE vaults(
--   id INT NOT NULL AUTO_INCREMENT,
--   creatorId VARCHAR(255) NOT NULL,
--   name VARCHAR(255) NOT NULL,
--   img VARCHAR(255) NOT NULL,
--   description VARCHAR(255) NOT NULL,
--   isPrivate TINYINT NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY (creatorId)
--     REFERENCES kprofile(id)
--     ON DELETE CASCADE
-- )
-- CREATE TABLE vaultKeeps(
--   id INT NOT NULL AUTO_INCREMENT,
--   creatorId VARCHAR(255) NOT NULL,
--   vaultId INT NOT NULL,
--   keepId INT NOT NULL,
--   PRIMARY KEY (id),

--   FOREIGN KEY (creatorId)
--     REFERENCES kprofile(id)
--     ON DELETE CASCADE,

--   FOREIGN KEY (vaultId)
--     REFERENCES vaults(id)
--     ON DELETE CASCADE,
  
--   FOREIGN KEY (keepId)
--     REFERENCES keeps(id)
--     ON DELETE CASCADE
-- )